// Generated by gencpp from file move_base_msgs/hgpathplanner.msg
// DO NOT EDIT!


#ifndef MOVE_BASE_MSGS_MESSAGE_HGPATHPLANNER_H
#define MOVE_BASE_MSGS_MESSAGE_HGPATHPLANNER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <move_base_msgs/pathpoint.h>

namespace move_base_msgs
{
template <class ContainerAllocator>
struct hgpathplanner_
{
  typedef hgpathplanner_<ContainerAllocator> Type;

  hgpathplanner_()
    : header()
    , points()
    , info()  {
    }
  hgpathplanner_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::move_base_msgs::pathpoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::move_base_msgs::pathpoint_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::move_base_msgs::hgpathplanner_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_base_msgs::hgpathplanner_<ContainerAllocator> const> ConstPtr;

}; // struct hgpathplanner_

typedef ::move_base_msgs::hgpathplanner_<std::allocator<void> > hgpathplanner;

typedef boost::shared_ptr< ::move_base_msgs::hgpathplanner > hgpathplannerPtr;
typedef boost::shared_ptr< ::move_base_msgs::hgpathplanner const> hgpathplannerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_base_msgs::hgpathplanner_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_base_msgs::hgpathplanner_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_base_msgs::hgpathplanner_<ContainerAllocator1> & lhs, const ::move_base_msgs::hgpathplanner_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.points == rhs.points &&
    lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_base_msgs::hgpathplanner_<ContainerAllocator1> & lhs, const ::move_base_msgs::hgpathplanner_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_base_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_base_msgs::hgpathplanner_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_base_msgs::hgpathplanner_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_base_msgs::hgpathplanner_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_base_msgs::hgpathplanner_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_base_msgs::hgpathplanner_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_base_msgs::hgpathplanner_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_base_msgs::hgpathplanner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f733303459dce02f6b5202bfc07ecd5";
  }

  static const char* value(const ::move_base_msgs::hgpathplanner_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f733303459dce02ULL;
  static const uint64_t static_value2 = 0xf6b5202bfc07ecd5ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_base_msgs::hgpathplanner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_base_msgs/hgpathplanner";
  }

  static const char* value(const ::move_base_msgs::hgpathplanner_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_base_msgs::hgpathplanner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"move_base_msgs/pathpoint[] points\n"
"string info\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: move_base_msgs/pathpoint\n"
"# A wrapper for a single path point\n"
"geometry_msgs/PoseStamped point\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::move_base_msgs::hgpathplanner_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_base_msgs::hgpathplanner_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hgpathplanner_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_base_msgs::hgpathplanner_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_base_msgs::hgpathplanner_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::move_base_msgs::pathpoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_BASE_MSGS_MESSAGE_HGPATHPLANNER_H
